[build]
  publish = "dist/"
  command = "yarn build:network --verbose --history"

[context.deploy-preview.environment]
  CURRENT_NETWORK = "dalinet"

[context.branch-deploy.environment]
  CURRENT_NETWORK = "dalinet"

# Dalinet
[context."develop".environment]
  CURRENT_NETWORK = "dalinet"

# Dalinet
[context."dalinet".environment]
  CURRENT_NETWORK = "dalinet"

# Sandbox
[context."sandbox".environment]
  CURRENT_NETWORK = "sandbox"

# Livenet
[context."livenet".environment]
  CURRENT_NETWORK = "livenet"

# Livenet
[context."master".environment]
  CURRENT_NETWORK = "livenet"

# SPA explorer application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
