# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  # /!\ Beware! This named job is called from "GUN/reserve" and "HUB" CircleCI jobs
  # for the production environment.
  # If you rename it, you have to update the build script of the other projects
  build-deploy: # todo: split this into small jobs

    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/explorer

    steps:

      - checkout

      - run:
          name: Update npm to @latest
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build --network devnet --verbose --base https://unik-name.github.io/explorer/

      - run:
          name: Deploy
          shell: /bin/sh
          command: ./.circleci/deploy.sh

####################################
## Workflows
####################################
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - master

####################################
## Notifications
####################################
# It's a 1.0 CircleCI config, but it's still working
# See https://discuss.circleci.com/t/experimental-branch-notifications-from-1-0/12964
experimental:
  notify:
    branches:
      only:
        - master