name: Mirror 'develop' and 'dalinet' branches (develop -> dalinet)

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "unik-name/explorer"
          source_branch: "develop"
          destination_branch: "dalinet"
          github_token: ${{ secrets.GITHUB_TOKEN }}
